### PR TITLE
WIP feature/scheduled auto sprint

### PR DESCRIPTION
**Pull request by ltankey**
**WIP -- IS NOT FINISHED  -- DO NOT MERGE **

  Add environment to parse scheduled repos

    This stops persistence blocking #18

  Initial commit for #18

    This started as a policy but then changed once it became clear it would never get a callback

    Add project support and some improvements for #18

    Refactor the way we load config, partly answering #24

### CODE REVIEW

**Comment by monkeypants** [comment]
but I want to merge it, I like it ;)

**Comment by monkeypants** [comment]
So, @ltankey what should we do with this old PR?

**Comment by monkeypants** [comment]
fair enough :)

**Comment by ltankey** [comment]
OTBE :) worth revisiting

**Pull request closed without merging**
